"use client";

import { Briefcase, Heart, BookOpen, Wallet, Target, Sparkles } from "lucide-react";
import { useData } from "@/context/DataContext";

export default function TimelinePage() {
  const { goals } = useData();

  const getIcon = (cat: string) => {
    if (cat === "Career") return <Briefcase className="w-5 h-5" />;
    if (cat === "Finance") return <Wallet className="w-5 h-5" />;
    if (cat === "Health") return <Heart className="w-5 h-5" />;
    if (cat === "Learning") return <BookOpen className="w-5 h-5" />;
    return <Target className="w-5 h-5" />;
  };

  const getColor = (cat: string) => {
    if (cat === "Career") return { color: "bg-blue-500", light: "bg-blue-50" };
    if (cat === "Finance") return { color: "bg-amber-500", light: "bg-amber-50" };
    if (cat === "Health") return { color: "bg-rose-500", light: "bg-rose-50" };
    if (cat === "Learning") return { color: "bg-emerald-500", light: "bg-emerald-50" };
    return { color: "bg-purple-500", light: "bg-purple-50" };
  };

  const milestones = goals.filter(g => g.deadline).map(g => {
    const d = new Date(g.deadline!);
    return {
      date: d.toLocaleDateString(undefined, { month: 'short', year: 'numeric' }),
      rawDate: d.getTime(),
      title: g.title,
      description: g.description,
      category: g.category,
      icon: getIcon(g.category),
      color: getColor(g.category).color,
      lightColor: getColor(g.category).light,
    };
  }).sort((a, b) => a.rawDate - b.rawDate);

  return (
    <div className="space-y-8 animate-fade-up">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-6 rounded-2xl border shadow-sm">
        <div>
          <h1 className="text-2xl font-extrabold tracking-tight">Your Future Timeline</h1>
          <p className="text-sm text-muted-foreground mt-1 max-w-xl">
            See how your current choices shape your future. This projection is generated by analyzing your habits and goals.
          </p>
        </div>
        <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-3 py-1.5 rounded-full text-xs font-bold shrink-0 self-start md:self-center border border-primary/20">
          <Sparkles className="w-3.5 h-3.5" /> AI Generated
        </div>
      </div>

      <div className="relative border-l-[3px] border-border ml-6 md:ml-10 space-y-12 pb-8">
        {milestones.length === 0 ? (
          <div className="bg-muted/50 rounded-2xl p-6 border border-border/50 text-center ml-4">
            <p className="text-sm text-muted-foreground font-semibold">Add goals with deadlines to see your timeline!</p>
          </div>
        ) : milestones.map((milestone, index) => (
          <div key={index} className="relative pl-8 md:pl-12 group">
            {/* Timeline Dot with Icon */}
            <div className={`absolute left-[-23px] top-0 h-11 w-11 rounded-full ${milestone.color} text-white flex items-center justify-center ring-[6px] ring-[var(--background)] shadow-sm transition-transform duration-300 group-hover:scale-110`}>
              {milestone.icon}
            </div>

            <div className="bg-white rounded-2xl border border-border shadow-sm overflow-hidden group-hover:shadow-md transition-shadow group-hover:border-primary/20">
              <div className="flex flex-col md:flex-row">
                {/* Desktop date sidebar */}
                <div className={`hidden md:flex flex-col justify-center items-center w-32 shrink-0 ${milestone.lightColor} border-r border-border p-4`}>
                  <p className="font-bold text-sm text-center">{milestone.date.split(" ")[0]}</p>
                  <p className="text-xl font-extrabold text-foreground/80">{milestone.date.split(" ")[1]}</p>
                </div>

                <div className="flex-1 p-5 md:p-6">
                  {/* Mobile date badge */}
                  <div className="md:hidden inline-block px-3 py-1 rounded-full bg-muted text-xs font-bold mb-3">
                    {milestone.date}
                  </div>

                  <div className="flex justify-between items-start gap-4 flex-wrap mb-2">
                    <h2 className="text-xl font-bold">{milestone.title}</h2>
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider bg-muted text-muted-foreground border border-border">
                      {milestone.category}
                    </span>
                  </div>
                  
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {milestone.description}
                  </p>
                </div>
              </div>
            </div>
          </div>
        ))}

        {/* Future continuation marker */}
        <div className="relative pl-8 md:pl-12 pt-4">
          <div className="absolute left-[-15px] top-4 h-7 w-7 rounded-full bg-muted flex items-center justify-center ring-[6px] ring-[var(--background)]">
            <Target className="w-3.5 h-3.5 text-muted-foreground" />
          </div>
          <div className="bg-muted/50 rounded-2xl p-4 border border-border/50 text-center">
            <p className="text-sm text-muted-foreground font-semibold italic">The journey continues...</p>
          </div>
        </div>
      </div>
    </div>
  );
}
